### ISSUE TITLE
Technische documentatie bij ICDD

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/COINS-3.0-ICDD#11]
Opdracht van beheercommissie: Stel technische documentatie op bij ICDD.

Mijn blonde vragen aan expertcommissie:
Is dit nodig

1. Documentatie zodat een softwareleverancier weet hoe hij zijn software moet inrichten om de ICDD container samen te stellen en/of uit te pakken.
2. Documentatie voor een datamodelleur
3. Een informatiemodel met of zonder dereferencable URI's????
4. Ondersteunende code / ????
5. Wat nog meer?

Taakstellend budget: 15.000 euro
Deadline: januari 2021

**Comment by nreyngou** [comment]
Wellicht ook nog deze:

ILS eisen die een opdrachtgever moet opnemen om op de juiste manier ICDD uit te vragen?

**Comment by ElisabethDeVries** [comment]
3 ontologiën: dereferencable publiceren.

voorwaarden voor ontologiën ín de container - levels uit de NTA 8035, keuze maken?
> Scope voor deze technische documentatie:  puur ICDD, niet de NTA meenemen.

aanbeveling voor een syntax?

Versie management?

**Comment by ElisabethDeVries** [comment]
Wat heeft een softwareleverancier nodig om ICDD te kunnen implementeren?

1. Use case
Uitwisselscenario: 
> aanname: de gegevens worden met elkaar uitgewisseld, er is geen "shared data"
Areaalgegevens uitiwsselen: Geometrie, data en "documenten"

2. Beheer van de links
> Waar bouw je die links op? Verwijzigingen tussen tools, waar liggen die dan? In je projectmanagementtool moet je de links kunnen leggen? Om een eenduidig pakket te kunnen genereren moet je kiezen vanwaar je de links opbouwt, vooral als je met meerdere tools werkt. Gevaar van "niet beheren" van de relaties is een kluwen van links genereren
> softwareleverancier met of zonder kennis van linked data? 

3. Regels voor gebruik deep links
Wanneer het algemene mechanisme gebruiken van een "identifier", wanneer deep links? Deep links > alleen gebruiken bij geometrie

4. softwareleverancier wil voorbeelden hebben

5. Verificatieservice. Een een manier om te controleren of het klopt > 1. Zip controle op de ICDD file, is het een zip file kloppen de mappen, typeringen enzovoorts.  2. Syntax is de indexfile ok?  klopt het modelmatig qua ICDD, level 3 is zijn de links tegenstrijdig, verwijzen ze ergens naar?

6. Dereferencable de 3 ontologiën uit icdd publiceren

Buiten scope
. >bij ontwikkelen ICDD ondersteunende tooling > > misschien "tussen-export" ontwikkelen in csv?

**Comment by ElisabethDeVries** [comment]
En voor de eindgebruiker

> ILS specificaties bij ICDD?
is erg organisatiespecifiek. Denk aan voorkeurskeuze voor serialisatie? 
> Specs voor software die icdd moeten kunnen lezen of genereren > of moet je een eigen beheertool hebben om icdd te kunnen uitpakken en samenstellen > ook erg organisatiespecifiek

**Comment by ElisabethDeVries** [comment]
Documentatie is opgesteld, issue wordt gesloten
