### ISSUE TITLE
richtlijnen gewenst hoe organisatie specifieke OTL's kunnen aansluiten op de sectorbrede (IMBOR) OTL

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/COINS-3.0-ICDD#12]
Vanuit verschillende organisaties leven er vragen wat het beste scenario is om een organisatie specifieke OTL aan te sluiten op een sectorbrede OTL (zoals IMBOR OTL)

**Comment by ElisabethDeVries** [comment]
Dit onderwerp zal moeten worden opgepakt binnen het DSGO; DigiGO is niet de beheerder van de ICDD standaard, dat is ISO. Deze repository zal worden gearchiveerd.
