### ISSUE TITLE
hernoemen github repo

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/COINS-3.0-ICDD#16]

**Comment by NielsHoffmann** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by NielsHoffmann** [comment]
@ElisabethKloren  als je wilt dat ik help met hernoemen moet je even een gil geven...

**Comment by ElisabethDeVries** [comment]
@NielsHoffmann graag! Wat met icdd-nl?

**Comment by ElisabethDeVries** [comment]
en gaan de links naar de respec's hierdoor ook wijzigen?

**Comment by NielsHoffmann** [comment]
ja, is dat een probleem? Volgens mij worden de oude url's wel doorgezet naar de nieuwe locatie. Maar het is dus slim om de nieuwe url's te gaan communiceren.
