### ISSUE TITLE
ICDD: RDF/XML versus NTA8035:Turtle

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/COINS-3.0-ICDD#3]
In ICDD part 1 paragraaf 4.3.1 “A container includes a header file in the top-level folder; this file complies with the RDF standard and is serialized in RDF/XML”
In de NTA wordt de voorkeur uitgesproken voor het Turtle serialisatie formaat (en wordt de ontologie als bijlage meegeleverd in turtle).
Dit is op zich niet een groot probleem, want het betreft alleen de serialisaties. Maar het is op zijn minst irritant dat je conform de specificaties met verschillende serialisaties moet werken.

**Comment by ElisabethDeVries** [comment]
De "documenten" (inhoud) die in de container vervoerd worden mogen wel uit turtle bestanden bestaan (of pdfs, of ifc, of......). 
Om te conformeren aan ICDD part 1 gebruiken we RDF/XML bij het opbouwen van de container & het linken van de documenten.

Voorstel best practice: in ICDD containers wordt altijd RDF/XML gebruikt voor zowel meta-data als data.
Om dit te ondersteunen wil BIM loket een RDF/XML serialisatie van de SHACL versie van het conceptuele meta model en top-level model toevoegen aan de NTA 8035.

**Comment by nreyngou** [comment]
**Niels Hoffmann**

Allen,

Er lopen hier dus twee discussies door elkaar….

De serialisatie volgorde  zoals die door tools wordt weggeschreven. Dit is van belang in de context van versie beheer van files in een git repository, maar niet een onderwerp waar we het verder over moeten hebben volgens mij.

Het andere is get serialisatie formaat, in dit geval rdf/xml vs turtle. ICDD schrijft rdf/xml voor, de NTA heeft een ‘lichte voorkeur’ voor Turtle. Mede omdat er in de rdf/xml serialisatie ruimte zit hoe triples weg te schrijven en dat kan in sommige gevallen tot problemen leiden.

Voor zover ik het begrijp gaat dat vooral over het gebruik van rdf:about
<rdf:Description rdf:about="http://www.example.com/2002/04/products#item10245">
versus rdf:ID
<rdf:Description rdf:ID="item10245">
Beide is valide conform de rdf/xml specificatie. Waarbij in de ID vorm het ID samengevoegd moet worden met de base uri die in het begin van het document is gedefinieerd.

Ik zou er dan voorstander van zijn om in de best practice op te nemen dat we rdf/xml serialisatie gebruiken voor alle files in een ICDD container, waarbij we wel willen dat de rdf:about vorm gebruikt wordt ipv de rdf:ID vorm. Eens?

@Michel,
Zijn er nog meer van dit soort ‘subtiliteiten’ in de rdf/xml vorm waar we rekening mee moeten houden?

Ik stel voor om deze discussie ook bij #issue 3 op github vast te leggen zodat het duidelijk is waar de ‘best practice’ vandaan komt….

**Bart Bink:**

Dat was Rob. De Turtle is consistent bij Protegé. Ik weet niet of dat ook geldt voor de RDF/XML variant, daar heb ik nooit behoefte aan gehad.

Is je vraag beantwoord?

Groeten,

**Rob van de Werken:**

Dat protege een ‘stabiele’ serialisatie maakt had ik genoemd, echter is die serialisatie wel in Turtle formaat. We waren het inderdaad eens dat er 1 serialisatie-vorm moet zijn voor zovel meta-data als data. En doordat ICDD RDF/XML voorschrijft, dat dan de voorkeur heeft. Echter zijn er 2 vormen van RDF/XML serialisatie, namelijk RDF/XML en RDF/XML-ABBREV.

**Niels Reyngoud:**

In het overleg van afgelopen vrijdag waren we met zijn allen vrij zeker van de keuze voor RDF/XML.
Het zou wel mooi zijn als het metaniveau en de data in dezelfde serialisatietaal zijn uitgeschreven. We willen nu juist één logisch verhaal maken van ICDD+NTA.

Ik meende dat Bart vertelde dat als de RDF/XML serialisatie met Protege wordt gemaakt, dat deze dan wel altijd hetzelfde is.

Zou je het probleem met id en about kunnen toelichten?

**Michel Böhms:**

Denken Julie ook nog even over de RDF XML serialisatie.
Id en about gebruik levert vaak issues (zoals genoemde niet gedetermineerdheid, er is 1 met id, welke kan steeds anders zijn).

Kunnen we niet icdd p1 rdf/xml negeren en toch Turtle hanteren?

Of anders toch mix: meta : rdfxml, niet-meta : turtle…?

Dank voor ideeën!

**Comment by ElisabethDeVries** [comment]
Is het niet-compact zijn van RDF/XML een reden om toch voor turtle bestandsformaat te kiezen bij toepassing van ICDD in combinatie met NTA 8035? Gezien de ervaringen met het grote volume van dataleveringen met COINS 2.0.

**Comment by ElisabethDeVries** [comment]
**Michel Böhms**:
Ja maar er zijn ook andere redenen
- mensvriendelijkheid
- minder variantie (meer determinatie), oa door willekeur about/id etc.

Heb nog geprobeerd icdd p1 te verbreden maar dit lukt om procesredenen niet.

Dus
Of we kiezen voor 1 consistente serialisatie over meta en normaal
Of we kiezen rdf/XML (abbrev.) voor meta en bv Turtle voor content


Kreeg pas nog opm. van TQ mbt RDF/XML in de trant van “wie gebruikt dat in de praktijk…”?

**Comment by ElisabethDeVries** [comment]
Voorstel: 

Gebruik RDF/XML voor het ICDD pakketje en 
Formaat naar keuze in de bijgevoegde documenten: er is immers geen reden om dwingend iets voor te schrijven, de betekenis is hetzelfde ongeacht de codeertaal. 
Met deze keuze volgen we ICDD en de gangbare praktijk in Nederland.

**Comment by NielsHoffmann** [comment]
Probleem blijft dat als je het serialisatie formaat in de container vrij laat je het extra lastig maakt voor software implementaties. Wat kunnen die wel/niet verwachten. Er moet meer logica geschreven worden om uit te vinden welke serialisatie gebruikt is en de documenten op de juiste manier te parsen.

**Comment by bartbink** [comment]
Precies. In ons overleg hebben we toen geconcludeerd dat het gebruik van RDF/XML over de hele linie softwareondersteuning makkelijker maakt door de consistentie en bekendheid met XML.

Side note was dat RDF/XML in verschillende smaken wordt gegenereerd vanuit editors en dan ook nog, bij TopBraid, een niet vaste volgorde of structuur heeft. Protege zou dat wel hebben.

We hebben de vergadering afgesloten concluderend dat we XML zouden gebruiken over de hele linie om in lijn te zijn met ICDD, ondanks dat een Turtle serialisatie consistenter zou zijn en leesbaar door de mens. Hierbij namen we in ogenschouw dat het te laat was in het standaardisatieproces om de serialisatie van de ICDD te wijzigen.

Ik ben wel voorstander van één smaak in een ICDD pakket, of RDF/XML of Turtle. De keuze komt dan, wat mij betreft hierop neer:


  *   RDF/XML in lijn met ICDD en waarschijnlijk drempel verlagend voor softwareondersteuning.
  *   Turtle omdat het consistenter is en mens leesbaar. Software moet dan wel Turtle kunnen parsen.

Korte termijn redenatie RDF/XML, lange termijn wat mij betreft Turtle (voorwaardelijk de aanpassing naar Turtle van de ICDD).

Dat is wat ik denk.

Groeten,

Bart.

**Comment by nreyngou** [comment]
Ik kan me vinden in de argumentatie van Niels en Bart. Eén serialisatie kiezen lijkt me heel erg wenselijk in het kader van implementeerbaarheid door softwareleveranciers. Turtle krijgen we er op de korte termijn niet meer in bij ICDD, dus dan blijft voor de korte termijn alleen RDF/XML over, voor zower de container als de data...

**Comment by ElisabethDeVries** [comment]
Dan concludeer ik hierbij: ICDD pakketjes, in combinatie met data conform NTA 8035, gebruiken als bestandstype "RDF/XML"

**Comment by NielsHoffmann** [comment]
Mail van Michel Bohms, d.d. 16-03-2020:

Even een update vanuit ICDD.

Er wordt nu gekeken of er een 2e conformance class gedefinieerd kan worden die de serialisatie meer flexibel maakt.
Deze CC schrijft dan niet strikt RDF/XML voor maar iha een RDF-serialisatie met W3C recommendation status.

Dit biedt denk ik ruimte voor COINS3.0 ook.

VG Michel & Benno

**Comment by ElisabethDeVries** [comment]
Dit schrijft GWSW over turtle versus RDF/XML:

De overwegingen bij RDF Turtle op een rij:
• De syntax is helder en ontworpen voor triples. In het alternatieve RDF/XML formaat kan subject als xml-attribuut
van xml-element <RDF:Description> en als xml-element onder <RDF:Description> voorkomen. Dat maakt het
complex. XML sluit als structuur niet goed aan, is oorspronkelijk niet voor triples bedoeld.
• RDF Turtle heeft geen beperking in URI’s (lokale naamgeving/karakters);
• RDF Turtle heeft compacte syntax voor toevoegen van eenheden en taal;
• RDF Turtle wordt algemeen gebruikt, de Turtle-syntax komt ook terug in de SPARQL syntax (de querytaal voor
Triplestores);
• Voor het alternatieve RDF/XML formaat zou gebruik van XML-parsers een voordeel kunnen zijn maar die blijken
nauwelijks bruikbaar;
