### ISSUE TITLE
Combining ICDD and MDTO

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/COINS-3.0-ICDD#5]
Ik weet dat ICDD part2 nog op zich laat wachten, maar ik loop wel meteen tegen vragen aan hoe ik mijn informatie verder moet typeren naast het feit dat ik op basis van de constructies in ICDD Part1 de relaties aan kan duiden. (dus ik kan beschrijven dat een rapport x gaat over asset y) Maar ik wil dat rapport dus ook van metadata voorzien conform TMLO (waar overigens dubbelingen in zitten, want icdd kent ct:filetype, ct:filename properties die ook in TMLO voorkomen…) Het zou volgens mij enorm helpen als de NTA daar ook al best practices voor beschrijft. Lopen anderen hier al tegenaan?

Hoofdstuk 5 in ICDD: The following requirements apply to the extendability of the ontologies:
1.	No extensions are permitted, therefore the Index.rdf file and any Link dataset file may only contain individuals that are in compliance with the classes as specified by Container.rdf and Linkset.rdf.

**Comment by ElisabethDeVries** [comment]
Relatie met Kenniskaart duurzame archivering oid van BIM loket

BIM loket zou een mapping kunnen maken tussen TMLO en ICDD 4.4.2; en een aanvullende ontologie kunnen maken hierbij (contactpersoon zoeken hiervoor)

**Comment by NielsHoffmann** [comment]
Er is in 2018 een rapport/kenniskaart 'digitaal archiveren' opgeleverd. Dit onderwerp raakt daar aan...

**Comment by NielsHoffmann** [comment]
de FDIS van Part2 levert dus wel input op voor dit issue. Namelijk dat part 2 eigenlijk ook alleen maar gaat over de nadere specificatie van de links in de linkset ontologie. Daarmee kun je in principe dus concluderen dat je aanvullende ontologieen plus de relaties van die ontologieen met de andere documenten allemaal in de payload documents folder moet opnemen?

**Comment by NielsHoffmann** [comment]
TMLO gaat opgevolgd worden door MDTO (Metagegevens voor Duurzaam Toegankelijke Overheidsinformatie) dus dit issue moet in dat verband verder opgepakt worden

**Comment by ElisabethDeVries** [comment]
De restricties in ICDD werken niet goed met deze wens. Daarom stellen we voor om tóch een uitbreiding te maken van de metadata in icdd.


Deze restrictie: Hoofdstuk 5 in ICDD: The following requirements apply to the extendability of the ontologies:

No extensions are permitted, therefore the Index.rdf file and any Link dataset file may only contain individuals that are in compliance with the classes as specified by Container.rdf and Linkset.rdf.

**Comment by ElisabethDeVries** [comment]
Dit onderwerp zal moeten worden opgepakt binnen het DSGO; DigiGO is niet de beheerder van de ICDD standaard, dat is ISO. Deze repository zal worden gearchiveerd.
