### ISSUE TITLE
Aanbevelingen TriG/TriX serialisatie

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/COINS-3.0-ICDD#8]
We merken dat bij het opstellen van OTL's vaak meerdere graphs gebruikt worden (voor domeinen, definities e.d.). In een Turtle en/of RDF/XML bestand kan maar een graph opgenomen worden.
Om een ontologie met meerdere graphs in samenhang te kunnen serialiseren is TriG of TriX een mogelijke oplossing. 
Hiervoor is een best practices gewenst.

**Comment by bartbink** [comment]
Ik heb gekeken naar de serialisatie, het is i.d.d. goed leesbaar. De tool waar ik mee werk, TopBraid Composer ME kan graphs niet exporteren. Bij Protege zie ik dat ook niet zo snel. Is daar voor het laatste programma een pluin voor?

En verder, is het erg om Graphs los op te stellen? Handig voor beheer, publicatie en gebruik. TriG biedt de mogelijkheid het geheel aan Graphs als set aan te bieden, dat wel.

**Comment by NielsHoffmann** [comment]
Er is inderdaad nog beperkte ondersteuning vanuit tooling. Ik begreep dat TopBraid dat in de volgende versie wel gaat verbeteren.
Het voordeel van meerdere graphs in 1 file is dat expliciet duidelijk is dat de ontologie uit meerdere graphs bestaat. Als de ontologie in meerdere files verspreid wordt loop je altijd de kans dat je een file mist zonder dat je dat realiseert en daarmee naar een incomplete ontologie kijkt.

**Comment by ElisabethDeVries** [comment]
Dit onderwerp zal moeten worden opgepakt binnen het DSGO; DigiGO is niet de beheerder van de ICDD standaard, dat is ISO. Deze repository zal worden gearchiveerd.
