### ISSUE TITLE
Metadata elementen voor OTL's 

### ISSUE THREAD

**Issue by NielsHoffmann** [bimloket/COINS-3.0-ICDD#9]
er is behoefte aan een 'best practice' welke metadata elementen er typisch opgenomen moeten worden om een OTL te beschrijven. 
Dit komt voort uit de vraag van gemeente Amsterdam over de imbor ontologie, maar is natuurlijk breed van toepassing op alle OTL's die opgesteld worden. Het zou helpen als die met een vergelijkbare set metadata elementen gedocumenteerd worden.

**Comment by redmer** [comment]
Bedoel je dan de omschrijving van de OTL zelf, zoals:

- naam
- versie
- wanneer opgesteld
- door wie opgesteld
- contactinformatie
- gebruikte vocabulaires
- talen van de definities

**Comment by ElisabethDeVries** [comment]
Dit onderwerp zal moeten worden opgepakt binnen het DSGO; DigiGO is niet de beheerder van de ICDD standaard, dat is ISO. Deze repository zal worden gearchiveerd.
